function Hd = wall_filter
%FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.1 and DSP System Toolbox 24.1.
% Generated on: 26-Oct-2025 12:37:01

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 1024;  % Sampling Frequency

N  = 2;    % Order
Fc = 100;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter', ...
    'SystemObject', true,...
    UseLegacyBiquadFilter=true);

% [EOF]



