# config.py

EXE_PATH = r"C:\Uni\Embedded\Project Sarah\rplidar_sdk_master\output\x64\Debug\ultra_simple.exe"
PORT = "COM9"
BAUD = "460800"

XY_RESOLUTION = 0.02  # meters per grid cell
EXTEND_AREA = 3.0

ROBOT_DIAMETER = 0.30
SAFETY_MARGIN = 0.05
DOOR_THRESHOLD = ROBOT_DIAMETER + SAFETY_MARGIN
MIN_VALID_RANGE = 0.05

CLUSTER_EPS = 0.25
CLUSTER_MIN_SAMPLES = 1
MIN_DOORWAY_SEPARATION = 0.7
ARRIVAL_RADIUS = 0.4
DETECTION_COOLDOWN = 12

SIM_DRIVE_SPEED = 0.20
RING_RADIUS_M = 1
SAMPLE_COUNT = 360
WORKER_SCAN_SECONDS = 1.0

UI_PAUSE = 0.05
